from typing import TypedDict, Dict, Any, List

class AgentState(TypedDict):
    """
    Represents the internal state of the LangGraph multi-signal reasoning pipeline.
    This tracks the item context and intermediate signals gathered by each node before synthesis.
    """
    item_id: str
    url_slug: str
    item_name: str
    frame_name: str
    component_type: str
    
    # Inputs collected from Database
    price_history: List[Dict[str, Any]]
    vault_info: Dict[str, Any]
    patchlogs: List[Dict[str, Any]]
    
    # Intermediate signal values
    trend_signal: Dict[str, Any]      # Generated by trend_node
    vault_signal: Dict[str, Any]      # Generated by vault_node
    patch_signal: Dict[str, Any]      # Generated by patch_node
    
    # Final outputs
    recommendation: str               # 'SELL' or 'HOLD'
    reasoning: str                    # Synthesis explanation
